services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - PORT=8000

  db:
    image: postgres
    container_name: postgres_box
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: algodb
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "8080:5432"
